name: flutter_cgm
description: "Library for displaying CGM files in Flutter"
version: 0.0.2
homepage:
repository: https://github.com/insufficientFunding/flutter_cgm

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  cgm: ^0.0.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
